variable "env" {}
variable "project_id" {}
variable "cluster_region" {}
variable "cluster_name" {}
variable "network_name" {}
variable "subnetwork_name" {}
variable "node_labels" {}
variable "node_tags" {}
variable "default_node_pool" {}
